# Generated by Django 3.1 on 2023-03-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_burger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burger',
            old_name='pImage',
            new_name='bImage',
        ),
    ]
